# Generated by Django 2.0.1 on 2018-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('prices', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('authors', models.CharField(blank=True, max_length=2000)),
                ('publisher', models.CharField(blank=True, max_length=500)),
                ('year', models.IntegerField(blank=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('thumbnail_small', models.ImageField(blank=True, default='None', null=True, upload_to='')),
                ('thumbnail', models.ImageField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2000px-No_image_available.svg.png', upload_to='')),
                ('quantity', models.PositiveIntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='subject',
            field=models.ForeignKey(on_delete='CASCADE', to='book.SubjectModel'),
        ),
    ]
