# Generated by Django 2.0.6 on 2018-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookordersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionBooksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=999)),
                ('Author', models.CharField(max_length=999)),
                ('Quantity', models.CharField(max_length=999)),
                ('Price', models.CharField(max_length=999)),
                ('Location', models.CharField(max_length=999)),
                ('Isbn', models.CharField(max_length=999)),
                ('EditionYear', models.CharField(max_length=999)),
                ('Publisher', models.CharField(max_length=999)),
                ('Edition', models.CharField(max_length=999)),
                ('Cover', models.CharField(max_length=999)),
                ('Subject', models.CharField(max_length=999)),
                ('Pages', models.CharField(max_length=999)),
                ('Language', models.CharField(max_length=999)),
                ('Display', models.CharField(max_length=999)),
            ],
        ),
    ]
